#!/bin/bash
set -euE

$ROOTCMD groupadd --gid 1000 vagrant
$ROOTCMD useradd --uid 1000 --gid 1000 --shell /bin/bash vagrant
mkdir -p $target/home/vagrant/.ssh
cat > $target/home/vagrant/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
chmod -R go= $target/home/vagrant
chown -R 1000:1000 $target/home/vagrant

cat > $target/etc/sudoers.d/90-vagrant << EOF
vagrant ALL=(ALL) NOPASSWD: ALL
EOF

echo root:vagrant | $ROOTCMD chpasswd
echo vagrant:vagrant | $ROOTCMD chpasswd

# https://developer.hashicorp.com/vagrant/docs/boxes/base#ssh-tweaks
ainsl /etc/ssh/sshd_config 'UseDNS no'

$ROOTCMD systemctl enable generate-sshd-host-keys.service
